DROP TABLE ADMINISTRATIVO CASCADE CONSTRAINTS ;
DROP TABLE AFP CASCADE CONSTRAINTS ;
DROP TABLE CATEGORIA CASCADE CONSTRAINTS ;
DROP TABLE COMUNA CASCADE CONSTRAINTS ;
DROP TABLE DETALLE_VENTA CASCADE CONSTRAINTS ;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS ;
DROP TABLE MARCA CASCADE CONSTRAINTS ;
DROP TABLE MEDIO_PAGO CASCADE CONSTRAINTS ;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS ;
DROP TABLE PROVEEDOR CASCADE CONSTRAINTS ;
DROP TABLE REGION CASCADE CONSTRAINTS ;
DROP TABLE SALUD CASCADE CONSTRAINTS ;
DROP TABLE VENDEDOR CASCADE CONSTRAINTS ;
DROP TABLE VENTA CASCADE CONSTRAINTS ;


-- Tablas base

CREATE TABLE REGION (
    id_region  NUMBER(4) NOT NULL,
    nom_region VARCHAR2(225) NOT NULL,
    CONSTRAINT REGION_PK PRIMARY KEY (id_region)
);

CREATE TABLE COMUNA (
    id_comuna        NUMBER(4) NOT NULL,
    nom_comuna       VARCHAR2(100) NOT NULL,
    REGION_id_region NUMBER(4) NOT NULL,
    CONSTRAINT COMUNA_PK PRIMARY KEY (id_comuna),
    CONSTRAINT COMUNA_REGION_FK FOREIGN KEY (REGION_id_region)
        REFERENCES REGION(id_region)
);

CREATE TABLE AFP (
    id_afp  NUMBER(5) GENERATED BY DEFAULT AS IDENTITY
        (START WITH 210 INCREMENT BY 6) NOT NULL,
    nom_afp VARCHAR2(255) NOT NULL,
    CONSTRAINT AFP_PK PRIMARY KEY (id_afp)
);

CREATE TABLE SALUD (
    id_salud  NUMBER(4) NOT NULL,
    nom_salud VARCHAR2(40) NOT NULL,
    CONSTRAINT SALUD_PK PRIMARY KEY (id_salud)
);

CREATE SEQUENCE SEQ_SALUD
    START WITH 2050
    INCREMENT BY 10
    NOCACHE;

CREATE TABLE CATEGORIA (
    id_categoria     NUMBER(3) NOT NULL,
    nombre_categoria VARCHAR2(255) NOT NULL,
    CONSTRAINT CATEGORIA_PK PRIMARY KEY (id_categoria)
);

CREATE TABLE MARCA (
    id_marca     NUMBER(3) NOT NULL,
    nombre_marca VARCHAR2(25) NOT NULL,
    CONSTRAINT MARCA_PK PRIMARY KEY (id_marca)
);

CREATE TABLE MEDIO_PAGO (
    id_mpago     NUMBER(3) NOT NULL,
    nombre_mpago VARCHAR2(40) NOT NULL,
    CONSTRAINT MEDIO_PAGO_PK PRIMARY KEY (id_mpago)
);

CREATE TABLE PROVEEDOR (
    id_proveedor     NUMBER(5) NOT NULL,
    nombre_proveedor VARCHAR2(150) NOT NULL,
    rut_proveedor    VARCHAR2(12) NOT NULL,
    telefono         VARCHAR2(15) NOT NULL,
    email            VARCHAR2(200) NOT NULL,
    direccion        VARCHAR2(200) NOT NULL,
    COMUNA_id_comuna NUMBER(4) NOT NULL,
    CONSTRAINT PROVEEDOR_PK PRIMARY KEY (id_proveedor),
    CONSTRAINT PROVEEDOR_COMUNA_FK FOREIGN KEY (COMUNA_id_comuna)
        REFERENCES COMUNA(id_comuna)
);

-- Tabla empleado

CREATE TABLE EMPLEADO (
    id_empleado          NUMBER(4) NOT NULL,
    rut_empleado         VARCHAR2(12) NOT NULL,
    nombre_empleado      VARCHAR2(25) NOT NULL,
    apellido_paterno     VARCHAR2(25) NOT NULL,
    apellido_materno     VARCHAR2(25) NOT NULL,
    fecha_contratacion   DATE NOT NULL,
    sueldo_base          NUMBER(10,2) NOT NULL,
    bono_jefatura        NUMBER(10,2),
    activo               CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N')),
    tipo_empleado        VARCHAR2(20) CHECK (tipo_empleado IN ('ADMINISTRATIVO','VENDEDOR')),
    EMPLEADO_id_empleado NUMBER(4),  -- puede ser NULL (supervisor)
    SALUD_id_salud       NUMBER(4) NOT NULL,
    AFP_id_afp           NUMBER(5) NOT NULL,
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (id_empleado),
    CONSTRAINT EMPLEADO_AFP_FK FOREIGN KEY (AFP_id_afp)
        REFERENCES AFP(id_afp),
    CONSTRAINT EMPLEADO_SALUD_FK FOREIGN KEY (SALUD_id_salud)
        REFERENCES SALUD(id_salud),
    CONSTRAINT EMPLEADO_SUPERVISOR_FK FOREIGN KEY (EMPLEADO_id_empleado)
        REFERENCES EMPLEADO(id_empleado)
);

CREATE SEQUENCE SEQ_EMPLEADO
    START WITH 750
    INCREMENT BY 3
    NOCACHE;

-- Subtipo de empleado

CREATE TABLE ADMINISTRATIVO (
    EMPLEADO_id_empleado NUMBER(4) NOT NULL,
    CONSTRAINT ADMINISTRATIVO_PK PRIMARY KEY (EMPLEADO_id_empleado),
    CONSTRAINT ADMINISTRATIVO_EMPLEADO_FK FOREIGN KEY (EMPLEADO_id_empleado)
        REFERENCES EMPLEADO(id_empleado)
);

CREATE TABLE VENDEDOR (
    EMPLEADO_id_empleado NUMBER(4) NOT NULL,
    comision_venta       NUMBER(5,2) NOT NULL,
    CONSTRAINT VENDEDOR_PK PRIMARY KEY (EMPLEADO_id_empleado),
    CONSTRAINT VENDEDOR_EMPLEADO_FK FOREIGN KEY (EMPLEADO_id_empleado)
        REFERENCES EMPLEADO(id_empleado)
);

-- Tabla producto

CREATE TABLE PRODUCTO (
    id_producto            NUMBER(4) NOT NULL,
    nombre_producto        VARCHAR2(100) NOT NULL,
    precio_unitario        NUMBER(10,2) NOT NULL,
    origen_nacional        CHAR(1) CHECK (origen_nacional IN ('S','N')),
    stock_minimo           NUMBER(3) NOT NULL,
    activo                 CHAR(1) DEFAULT 'S' CHECK (activo IN ('S','N')),
    MARCA_id_marca         NUMBER(3) NOT NULL,
    CATEGORIA_id_categoria NUMBER(3) NOT NULL,
    PROVEEDOR_id_proveedor NUMBER(5) NOT NULL,
    CONSTRAINT PRODUCTO_PK PRIMARY KEY (id_producto),
    CONSTRAINT PRODUCTO_MARCA_FK FOREIGN KEY (MARCA_id_marca)
        REFERENCES MARCA(id_marca),
    CONSTRAINT PRODUCTO_CATEGORIA_FK FOREIGN KEY (CATEGORIA_id_categoria)
        REFERENCES CATEGORIA(id_categoria),
    CONSTRAINT PRODUCTO_PROVEEDOR_FK FOREIGN KEY (PROVEEDOR_id_proveedor)
        REFERENCES PROVEEDOR(id_proveedor)
);

-- Tabla venta

CREATE TABLE VENTA (
    id_venta             NUMBER(4) GENERATED BY DEFAULT AS IDENTITY
        (START WITH 5050 INCREMENT BY 3) NOT NULL,
    fecha_venta          DATE NOT NULL,
    total_venta          NUMBER(10,2) NOT NULL,
    MEDIO_PAGO_id_mpago  NUMBER(3) NOT NULL,
    EMPLEADO_id_empleado NUMBER(4) NOT NULL,
    CONSTRAINT VENTA_PK PRIMARY KEY (id_venta),
    CONSTRAINT VENTA_MEDIO_PAGO_FK FOREIGN KEY (MEDIO_PAGO_id_mpago)
        REFERENCES MEDIO_PAGO(id_mpago),
    CONSTRAINT VENTA_EMPLEADO_FK FOREIGN KEY (EMPLEADO_id_empleado)
        REFERENCES EMPLEADO(id_empleado)
);

CREATE TABLE DETALLE_VENTA (
    VENTA_id_venta       NUMBER(4) NOT NULL,
    PRODUCTO_id_producto NUMBER(4) NOT NULL,
    cantidad             NUMBER(6) NOT NULL,
    CONSTRAINT DETALLE_VENTA_PK PRIMARY KEY (PRODUCTO_id_producto, VENTA_id_venta),
    CONSTRAINT DETALLE_VENTA_VENTA_FK FOREIGN KEY (VENTA_id_venta)
        REFERENCES VENTA(id_venta),
    CONSTRAINT DETALLE_VENTA_PRODUCTO_FK FOREIGN KEY (PRODUCTO_id_producto)
        REFERENCES PRODUCTO(id_producto)
);

-- Poblar tabla REGION
INSERT INTO REGION (id_region, nom_region) VALUES (1, 'Región Metropolitana');
INSERT INTO REGION (id_region, nom_region) VALUES (2, 'Valparaíso');
INSERT INTO REGION (id_region, nom_region) VALUES (3, 'Biobío');
INSERT INTO REGION (id_region, nom_region) VALUES (4, 'Los lagos');

-- Poblar tabla AFP
INSERT INTO AFP (nom_afp) VALUES ('AFP Habitat');
INSERT INTO AFP (nom_afp) VALUES ('AFP Cumprum');
INSERT INTO AFP (nom_afp) VALUES ('AFP Provida');
INSERT INTO AFP (nom_afp) VALUES ('AFP PlanVital');

-- Poblar tabla SALUD
INSERT INTO SALUD (id_salud, nom_salud) VALUES (SEQ_SALUD.NEXTVAL, 'Fonasa');
INSERT INTO SALUD (id_salud, nom_salud) VALUES (SEQ_SALUD.NEXTVAL, 'Isapre Colmena');
INSERT INTO SALUD (id_salud, nom_salud) VALUES (SEQ_SALUD.NEXTVAL, 'Isapre Banmédica');
INSERT INTO SALUD (id_salud, nom_salud) VALUES (SEQ_SALUD.NEXTVAL, 'Isapre Cruz Blanca');

-- Poblar tabla EMPLEADO
INSERT INTO EMPLEADO (id_empleado, rut_empleado, nombre_empleado, apellido_paterno, apellido_materno, fecha_contratacion, sueldo_base, bono_jefatura, activo, tipo_empleado, EMPLEADO_id_empleado, SALUD_id_salud, AFP_id_afp)
VALUES (SEQ_EMPLEADO.NEXTVAL, '11111111-1', 'Marcela', 'González', 'Pérez', TO_DATE('15-03-2022', 'DD-MM-YYYY'), 950000, 80000, 'S', 'ADMINISTRATIVO', NULL, 2050, 210);

INSERT INTO EMPLEADO (id_empleado, rut_empleado, nombre_empleado, apellido_paterno, apellido_materno, fecha_contratacion, sueldo_base, bono_jefatura, activo, tipo_empleado, EMPLEADO_id_empleado, SALUD_id_salud, AFP_id_afp)
VALUES (SEQ_EMPLEADO.NEXTVAL, '22222222-2', 'José', 'Muñoz', 'Ramírez', TO_DATE('10-07-2021', 'DD-MM-YYYY'), 900000, 75000, 'S', 'ADMINISTRATIVO', NULL, 2060, 216);

INSERT INTO EMPLEADO (id_empleado, rut_empleado, nombre_empleado, apellido_paterno, apellido_materno, fecha_contratacion, sueldo_base, bono_jefatura, activo, tipo_empleado, EMPLEADO_id_empleado, SALUD_id_salud, AFP_id_afp)
VALUES (SEQ_EMPLEADO.NEXTVAL, '33333333-3', 'Verónica', 'Soto', 'Alarcón', TO_DATE('05-01-2020', 'DD-MM-YYYY'), 880000, 70000, 'S', 'VENDEDOR', 750, 2060, 228);

INSERT INTO EMPLEADO (id_empleado, rut_empleado, nombre_empleado, apellido_paterno, apellido_materno, fecha_contratacion, sueldo_base, bono_jefatura, activo, tipo_empleado, EMPLEADO_id_empleado, SALUD_id_salud, AFP_id_afp)
VALUES (SEQ_EMPLEADO.NEXTVAL, '44444444-4', 'Luis', 'Reyes', 'Fuentes', TO_DATE('01-04-2023', 'DD-MM-YYYY'), 560000, NULL, 'S', 'VENDEDOR', 750, 2070, 228);

INSERT INTO EMPLEADO (id_empleado, rut_empleado, nombre_empleado, apellido_paterno, apellido_materno, fecha_contratacion, sueldo_base, bono_jefatura, activo, tipo_empleado, EMPLEADO_id_empleado, SALUD_id_salud, AFP_id_afp)
VALUES (SEQ_EMPLEADO.NEXTVAL, '55555555-5', 'Claudia', 'Fernández', 'Lagos', TO_DATE('15-04-2023', 'DD-MM-YYYY'), 600000, NULL, 'S', 'VENDEDOR', 753, 2070, 216);

INSERT INTO EMPLEADO (id_empleado, rut_empleado, nombre_empleado, apellido_paterno, apellido_materno, fecha_contratacion, sueldo_base, bono_jefatura, activo, tipo_empleado, EMPLEADO_id_empleado, SALUD_id_salud, AFP_id_afp)
VALUES (SEQ_EMPLEADO.NEXTVAL, '66666666-6', 'Carlos', 'Navarro', 'Vega', TO_DATE('01-05-2023', 'DD-MM-YYYY'), 610000, NULL, 'S', 'ADMINISTRATIVO', 753, 2060, 210);

INSERT INTO EMPLEADO (id_empleado, rut_empleado, nombre_empleado, apellido_paterno, apellido_materno, fecha_contratacion, sueldo_base, bono_jefatura, activo, tipo_empleado, EMPLEADO_id_empleado, SALUD_id_salud, AFP_id_afp)
VALUES (SEQ_EMPLEADO.NEXTVAL, '77777777-7', 'Javiera', 'Pino', 'Rojas', TO_DATE('10-05-2023', 'DD-MM-YYYY'), 650000, NULL, 'S', 'ADMINISTRATIVO', 750, 2050, 210);

INSERT INTO EMPLEADO (id_empleado, rut_empleado, nombre_empleado, apellido_paterno, apellido_materno, fecha_contratacion, sueldo_base, bono_jefatura, activo, tipo_empleado, EMPLEADO_id_empleado, SALUD_id_salud, AFP_id_afp)
VALUES (SEQ_EMPLEADO.NEXTVAL, '88888888-8', 'Diego', 'Mella', 'Contreras', TO_DATE('12-05-2023', 'DD-MM-YYYY'), 620000, NULL, 'S', 'VENDEDOR', 750, 2060, 216);

INSERT INTO EMPLEADO (id_empleado, rut_empleado, nombre_empleado, apellido_paterno, apellido_materno, fecha_contratacion, sueldo_base, bono_jefatura, activo, tipo_empleado, EMPLEADO_id_empleado, SALUD_id_salud, AFP_id_afp)
VALUES (SEQ_EMPLEADO.NEXTVAL, '99999999-9', 'Fernanda', 'Salas', 'Herrera', TO_DATE('18-05-2023', 'DD-MM-YYYY'), 570000, NULL, 'S', 'VENDEDOR', 753, 2070, 228);

INSERT INTO EMPLEADO (id_empleado, rut_empleado, nombre_empleado, apellido_paterno, apellido_materno, fecha_contratacion, sueldo_base, bono_jefatura, activo, tipo_empleado, EMPLEADO_id_empleado, SALUD_id_salud, AFP_id_afp)
VALUES (SEQ_EMPLEADO.NEXTVAL, '10101010-0', 'Tomás', 'Vidal', 'Espinoza', TO_DATE('01-06-2023', 'DD-MM-YYYY'), 530000, NULL, 'S', 'VENDEDOR', NULL, 2050, 222);

--Poblar tabla MEDIO_PAGO
INSERT INTO MEDIO_PAGO (id_mpago, nombre_mpago) VALUES (11, 'Efectivo');
INSERT INTO MEDIO_PAGO (id_mpago, nombre_mpago) VALUES (12, 'Tarjeta Débito');
INSERT INTO MEDIO_PAGO (id_mpago, nombre_mpago) VALUES (13, 'Tarjeta Crédito');
INSERT INTO MEDIO_PAGO (id_mpago, nombre_mpago) VALUES (14, 'Cheque');

--Poblar tabla VENTA
INSERT INTO VENTA (fecha_venta, total_venta, MEDIO_PAGO_id_mpago, EMPLEADO_id_empleado)
VALUES (TO_DATE('12-05-2023', 'DD-MM-YYYY'), 225990, 12, 771);

INSERT INTO VENTA (fecha_venta, total_venta, MEDIO_PAGO_id_mpago, EMPLEADO_id_empleado)
VALUES (TO_DATE('23-10-2023', 'DD-MM-YYYY'), 524990, 13, 777);

INSERT INTO VENTA (fecha_venta, total_venta, MEDIO_PAGO_id_mpago, EMPLEADO_id_empleado)
VALUES (TO_DATE('17-02-2023', 'DD-MM-YYYY'), 466990, 11, 759);

--Tablas Pobladas
SELECT * FROM REGION;
SELECT * FROM AFP;
SELECT * FROM SALUD;
SELECT * FROM EMPLEADO;
SELECT * FROM MEDIO_PAGO;
SELECT * FROM VENTA;

--Informe 1
SELECT
    id_empleado AS IDENTIFICADOR,
    nombre_empleado || ' ' || apellido_paterno || ' ' || apellido_materno AS "NOMBRE COMPLETO",
    sueldo_base AS SALARIO,
    bono_jefatura AS BONIFICACION,
    sueldo_base + bono_jefatura AS "SALARIO SIMULADO"
FROM
    EMPLEADO
WHERE
    activo = 'S'
    AND bono_jefatura IS NOT NULL
ORDER BY
    sueldo_base + bono_jefatura DESC,
    apellido_paterno DESC;
    
--Informe 2
SELECT
    nombre_empleado || ' ' || apellido_paterno || ' ' || apellido_materno AS EMPLEADO,
    sueldo_base AS SUELDO,
    ROUND(sueldo_base * 0.08, 2) AS "POSIBLE AUMENTO",
    ROUND(sueldo_base * 1.08, 2) AS "SALARIO SIMULADO"
FROM
    EMPLEADO
WHERE
    sueldo_base BETWEEN 550000 AND 800000
ORDER BY
    sueldo_base ASC;

