DROP TABLE DOMINIO CASCADE CONSTRAINTS;
DROP TABLE TITULACION CASCADE CONSTRAINTS;
DROP TABLE PERSONAL CASCADE CONSTRAINTS;
DROP TABLE COMPANIA CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP TABLE IDIOMA CASCADE CONSTRAINTS;
DROP TABLE TITULO CASCADE CONSTRAINTS;
DROP TABLE GENERO CASCADE CONSTRAINTS;
DROP TABLE ESTADO_CIVIL CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;


CREATE TABLE REGION (
    id_region       NUMBER(2) GENERATED BY DEFAULT AS IDENTITY
        (START WITH 7 INCREMENT BY 2) PRIMARY KEY,
    nombre_region   VARCHAR2(25)  NOT NULL
);

CREATE TABLE ESTADO_CIVIL (
    id_estado_civil     VARCHAR2(2) PRIMARY KEY,
    descripcion_est_civ VARCHAR2(25) NOT NULL
);

CREATE TABLE GENERO (
    id_genero          VARCHAR2(3) PRIMARY KEY,
    descripcion_genero VARCHAR2(25) NOT NULL
);

CREATE TABLE TITULO (
    id_titulo         VARCHAR2(3) PRIMARY KEY,
    descripcion_titulo VARCHAR2(60) NOT NULL
);

CREATE TABLE IDIOMA (
    id_idioma     NUMBER(3) GENERATED BY DEFAULT AS IDENTITY
        (START WITH 25 INCREMENT BY 3) PRIMARY KEY,
    nombre_idioma VARCHAR2(30) NOT NULL
);

CREATE TABLE COMUNA (
    id_comuna     NUMBER(5) PRIMARY KEY,
    comuna_nombre VARCHAR2(25) NOT NULL,
    cod_region    NUMBER(3) NOT NULL,
    CONSTRAINT COMUNA_FK_REGION FOREIGN KEY (cod_region)
        REFERENCES REGION(id_region)
);

-- Crear secuencia para id_comuna
CREATE SEQUENCE SEQ_COMUNA
    START WITH 1101
    INCREMENT BY 6
    NOCACHE;

CREATE TABLE COMPANIA (
    id_empresa     NUMBER(5) PRIMARY KEY,
    nombre_empresa VARCHAR2(25) UNIQUE NOT NULL,
    calle          VARCHAR2(50),
    numeracion     NUMBER(5),
    renta_promedio NUMBER(10),
    pct_aumento    NUMBER(5,3),
    cod_comuna     NUMBER(5) NOT NULL,
    cod_region     NUMBER(3) NOT NULL,
    CONSTRAINT COMPANIA_FK_COMUNA FOREIGN KEY (cod_comuna)
        REFERENCES COMUNA(id_comuna),
    CONSTRAINT COMPANIA_FK_REGION FOREIGN KEY (cod_region)
        REFERENCES REGION(id_region)
);

-- Crear secuencia para id_empresa
CREATE SEQUENCE SEQ_EMPRESA
    START WITH 10
    INCREMENT BY 5
    NOCACHE;

CREATE TABLE PERSONAL (
    rut_persona     NUMBER(8) PRIMARY KEY,
    dv_persona      CHAR(1) NOT NULL,
    primer_nombre   VARCHAR2(25) NOT NULL,
    segundo_nombre  VARCHAR2(25),
    primer_apellido VARCHAR2(25) NOT NULL,
    segundo_apellido VARCHAR2(25),
    fecha_nacimiento DATE NOT NULL,
    email           VARCHAR(100),
    calle           VARCHAR2(50),
    numeracion      NUMBER(5),
    cod_comuna      NUMBER(5) NOT NULL,
    cod_region      NUMBER(2) NOT NULL,
    cod_estado_civil VARCHAR2(2) NOT NULL,
    cod_genero      VARCHAR2(3) NOT NULL,
    cod_empresa      NUMBER(2) NOT NULL,
    encargado_rut   NUMBER(8),
    CONSTRAINT PERSONAL_FK_COMPANIA FOREIGN KEY (cod_empresa)
        REFERENCES COMPANIA(id_empresa),
    CONSTRAINT PERSONAL_FK_COMUNA FOREIGN KEY (cod_comuna, cod_region)
        REFERENCES COMUNA(id_comuna, cod_region),
    CONSTRAINT PERSONAL_FK_ESTADO_CIVIL FOREIGN KEY (cod_estado_civil)
        REFERENCES ESTADO_CIVIL(id_estado_civil),
    CONSTRAINT PERSONAL_FK_GENERO FOREIGN KEY (cod_genero)
        REFERENCES GENERO(id_genero),
    CONSTRAINT PERSONAL_PERSONAL_FK FOREIGN KEY (encargado_rut)
        REFERENCES PERSONAL(rut_persona)
);

CREATE TABLE TITULACION (
    cod_titulo     VARCHAR2(3),
    persona_rut    NUMBER(8),
    fecha_titulacion DATE,
    CONSTRAINT TITULACION_PK PRIMARY KEY (cod_titulo, persona_rut),
    CONSTRAINT TITULACION_FK_PERSONAL FOREIGN KEY (persona_rut)
        REFERENCES PERSONAL(rut_persona),
    CONSTRAINT TITULACION_FK_TITULO FOREIGN KEY (cod_titulo)
        REFERENCES TITULO(id_titulo)
);

CREATE TABLE DOMINIO (
    id_idioma    NUMBER(3),
    persona_rut  NUMBER(8),
    descripcion  VARCHAR2(25),
    CONSTRAINT DOMINIO_PK PRIMARY KEY (id_idioma, persona_rut),
    CONSTRAINT DOMINIO_FK_IDIOMA FOREIGN KEY (id_idioma)
        REFERENCES IDIOMA(id_idioma),
    CONSTRAINT DOMINIO_FK_PERSONAL FOREIGN KEY (persona_rut)
        REFERENCES PERSONAL(rut_persona)
);

--Poblar tabla REGION
INSERT INTO REGION (nombre_region) VALUES ('ARICA Y PARINACOTA');
INSERT INTO REGION (nombre_region) VALUES ('METROPOLITANA');
INSERT INTO REGION (nombre_region) VALUES ('LA ARAUCANIA');

-- Poblar tabla IDIOMA
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Ingles');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Chino');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Aleman');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Espanol');
INSERT INTO IDIOMA (nombre_idioma) VALUES ('Frances');

-- Poblar tabla COMUNA
INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
VALUES (SEQ_COMUNA.NEXTVAL, 'Arica', 7);

INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
VALUES (SEQ_COMUNA.NEXTVAL, 'Santiago', 9);

INSERT INTO COMUNA (id_comuna, comuna_nombre, cod_region)
VALUES (SEQ_COMUNA.NEXTVAL, 'Temuco', 11);

-- Poblar tabla COMPANIA
INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
VALUES (10, 'CCyRojas', 'Amapolas', 506, 1857000, 0.5, 1101, 7);

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
VALUES (15, 'SenTTy', 'Los Alamos', 3490, 897000, 0.025, 1101, 7);

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
VALUES (20, 'Praxia LTDA', 'Las Camelias', 11098, 2157000, 0.035, 1107, 9);

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
VALUES (25, 'TIC spa', 'FLORES S.A.', 4357, 857000, NULL, 1107, 9);

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
VALUES (30, 'SANTANA LTDA', 'AVDA VIC. MACKENA', 106, 757000, 0.015, 1101, 7);

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
VALUES (35, 'FLORES Y ASOCIADOS', 'PEDRO LATORRE', 557, 589000, 0.015, 1107, 9);

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
VALUES (40, 'J.A. HOFFMAN', 'LATINA D.32', 509, 1857000, 0.025, 1113, 11);

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
VALUES (45, 'CAGLIARI D.', 'ALAMEDA', 206, 1857000, NULL, 1107, 9);

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
VALUES (50, 'Rojas HNOS LTDA', 'SUCRE', 106, 957000, 0.005, 1113, 11);

INSERT INTO COMPANIA (id_empresa, nombre_empresa, calle, numeracion, renta_promedio, pct_aumento, cod_comuna, cod_region)
VALUES (55, 'FRIENDS P. S.A', 'SUECIA', 506, 857000, 0.015, 1113, 11);


SELECT * FROM IDIOMA;
SELECT * FROM REGION;
SELECT * FROM COMUNA;
SELECT * FROM COMPANIA;
--Consulta para primera Simulacion de renta
SELECT
    nombre_empresa,
    calle || ' ' || numeracion AS "Direccion",
    renta_promedio,
    ROUND(renta_promedio * (1 + NVL(pct_aumento, 0)), 0) AS "Simulación de Renta"
FROM
    COMPANIA
ORDER BY
    renta_promedio DESC,
    nombre_empresa ASC;

--Consulta para segunda Simulacion de Renta   
SELECT
    id_empresa AS CODIGO,
    nombre_empresa AS EMPRESA,
    renta_promedio AS "PROM RENTA ACTUAL",
    CASE
        WHEN pct_aumento IS NOT NULL THEN pct_aumento + 0.15
        ELSE NULL
    END AS "PCT AUMENTADO EN 15%",
    CASE
        WHEN pct_aumento IS NOT NULL THEN renta_promedio * (pct_aumento + 0.15)
        ELSE NULL
    END AS "RENTA AUMENTADA"
FROM
    COMPANIA
ORDER BY 
    renta_promedio ASC,
    nombre_empresa ASC;

    
    