spring.application.name=authorization-server

server.port=9000

spring.security.oauth2.authorizationserver.issuer=http://localhost:9000

spring.security.oauth2.authorizationserver.client.bank-client.registration.client-id=bank-client
spring.security.oauth2.authorizationserver.client.bank-client.registration.client-secret={noop}BankSecret123
spring.security.oauth2.authorizationserver.client.bank-client.registration.client-authentication-methods[0]=client_secret_basic
spring.security.oauth2.authorizationserver.client.bank-client.registration.authorization-grant-types[0]=client_credentials
spring.security.oauth2.authorizationserver.client.bank-client.registration.scopes[0]=bank.read
spring.security.oauth2.authorizationserver.client.bank-client.registration.scopes[1]=bank.write