server:
  port: 8091

spring:
  application:
    name: bank-service

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: BANK_BATCH
    password: BankBatch123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  kafka:
    bootstrap-servers: 100.52.166.37:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: bank-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    topic:
      transacciones: bank-transacciones

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      transaccionesService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

  endpoint:
    health:
      show-details: always