spring.application.name=bff-mobile

# ===============================
# CONEXIÓN ORACLE
# ===============================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=BANK_BATCH
spring.datasource.password=BankBatch123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVIDOR
# ===============================
server.port=8082
backend.base-url=http://localhost:8091